version: 2

before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild
    - cargo fetch --locked

# builds:
#   - builder: rust
#     flags:
#       - --release
#     targets:
#       - x86_64-unknown-linux-gnu
#       - x86_64-apple-darwin
      # - x86_64-pc-windows-gnu

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}" 
    maintainer: "Intentt <paddler@intentt.io>"
    formats:
      - deb
      - apk
      - rpm

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
