[workspace]
resolver = "2"
members = ["integration", "paddler"]

[workspace.dependencies]
paddler = { path = "paddler" }

# [package.metadata.askama]
# template-dir = "templates"

[profile.release]
lto = true
codegen-units = 1
strip = true
rpath = false
panic = "unwind"