[workspace]
resolver = "2"
members = ["integration", "paddler"]

[workspace.dependencies]
paddler = { path = "paddler" }

[profile.release]
lto = true
codegen-units = 1
strip = true
rpath = false
panic = "unwind"

[patch.crates-io]
sfv = { git = "https://github.com/undef1nd/sfv.git", tag = "v0.9.4" }
