name: 'Builds rust project'
description: 'Builds rust project'

inputs:
  bin:
    description: 'Binary name'
    required: true
  profile:
    description: 'Profile used on build'
    required: false
    default: "release"
  features:
    description: 'Build features'
    required: false
    default: ""
  before:
    description: 'Before hook'
    required: false
    default: ""

outputs:
  bin:
    description: "Built binary"
    value: ${{ steps.files.outputs.bin }}

runs:
  using: "composite"
  steps:
    - id: files
      run: bash --noprofile --norc "${GITHUB_ACTION_PATH:?}/script.sh"
      shell: bash
      env:
        INPUT_BIN: ${{ inputs.bin }}
        INPUT_PROFILE: ${{ inputs.profile }}
        INPUT_FEATURES: ${{ inputs.features }}
        INPUT_BEFORE: ${{ inputs.before }}
