name: 'Builds and archives rust project'
description: 'Builds and archives rust project'
inputs:
  bin:
    description: 'Binary name'
    required: true
  profile:
    description: 'Profile used on build'
    required: false
    default: "release"
  features:
    description: 'Build features'
    required: false
    default: ""
  archive:
    description: 'Archive name (compressed on tar.gz)'
    required: false
    default: ""
  deb:
    description: '.deb file name (compressed on tar.gz)'
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - run: ./script.sh"
      shell: bash
