name: 'Archives rust project'
description: 'Archives rust project'
inputs:
  archive:
    description: 'Archive name (compressed on tar.gz)'
    required: false
    default: ""
  deb:
    description: '.deb file name'
    required: false
    default: ""
  path:
    description: 'Path to binary'
    required: true
    default: ""
  before:
    description: 'Before hook'
    required: false
    default: ""
  OS:
    description: 'OS to build on'
    required: true
    default: ""
    
outputs:
    archive:
      description: "Archived file in .tar.gz"
      value: ${{ steps.files.outputs.archive }}
    deb:
      description: "Archived file in .tar.gz"
      value: ${{ steps.files.outputs.deb }}
runs:
  using: "composite"
  steps:
    - id: files
      run: bash --noprofile --norc "${GITHUB_ACTION_PATH:?}/script.sh"
      shell: bash
      env:
        INPUT_ARCHIVE: ${{ inputs.archive }}
        INPUT_DEB: ${{ inputs.deb }}
        INPUT_PATH: ${{ inputs.path }}
        INPUT_BEFORE: ${{ inputs.before }}
        INPUT_OS: ${{ inputs.os }}