[package]
name = "integration"
version = "0.1.0"
edition = "2024"

[[test]]
name = "supervisor"
harness = false

[dependencies]
paddler = { path = ".." }
cucumber = "0.21.1"
serde_json = "1.0.140"
sysinfo = "0.35.0"
log = "0.4.27"
tokio = "1.44.2"
reqwest = "0.12.15"
anyhow = "1.0.98"
