[package]
name = "integration"
version = "0.1.0"
edition = "2021"

[dependencies]
cucumber = "0.21.1"
nix = "0.30.1"
reqwest = "0.12.15"
serde_json = "1.0.140"
sysinfo = "0.35.0"
tokio = "1.45.0"
log = "0.4.27"
paddler = { workspace = true }