name: Test Llama.cpp Integration

on:
  push:
    branches:
      - main
      - cicd
  pull_request:
    branches:
      - main
      - cicd

jobs:
  setup:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

  build:
    needs: setup
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      # - name: Add miri
      #   run: rustup +nightly component add miri

      - name: Build static files
        run: make esbuild

      # - name: Build with miri
      #   run: cargo build --features web_dashboard --release

  test:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run unit tests
        run: cargo test
